### PR TITLE
[Testing] Migrate to Cypress 10

### PR DESCRIPTION
**Pull request by yoshitaka7**
I upgraded Cypress by looking at the change log and migration guide.
Be aware that the update to version 10 has added Breaking changes.
However, most of the migration was guided by the cypress open command.
Also, after the migration, a yarn test was performed and all were passed.

### The main changes are noted below

- `cypress.json`, the cypress config file, has been changed to `cypress.config.js`.

> Using a `cypress.json` configuration file is no longer supported. Replace this configuration file with a `cypress.config.js`, `cypress.config.ts`, `cypress.config.cjs` or `cypress.config.mjs` file.

- The test file extension has been changed from `spec` to `cy`.
- Component test commands have been changed.

>  `cypress open-ct` and `cypress run-ct` commands have been deprecated. Use `cypress open --component` and `cypress run --component` instead. 

- The mount function in the component test has been changed from `mount` to `cy.mount`.
This does not seem essential, but I had to do this to get it to work.

### CODE REVIEW

**Comment by AleksandarDev** [comment]
@yoshitaka7 Thank you for your contribution. I've added @radovix to review you changes.

I quickly took a look and all seems fine except commands.ts in `cypress/support/commands.ts` is missing screenshot command which is present in commands.js file. Can we delete the typescript one and continue using as is?

**Comment by yoshitaka7** [comment]
@AleksandarDev 
Thanks for checking! I'll respond to the points you reviewed.
1. command.ts was unnecessary and was removed. (Generated during migration.) I also confirmed that the screenshots were saved in cypress-pending after removing commands.ts.
2. I forgot to mention the use of yarn during the upgrade, sorry. I removed the package-lock.json and ran the upgrade using yarn.

**Comment by AleksandarDev** [comment]
@yoshitaka7 linting is showing some errors:

```
/home/runner/work/react-starter/react-starter/cypress.config.js
Error:    1:44  error  Missing semicolon                                                       semi
Error:    8:14  error  Unexpected require()                                                    global-require
Error:    8:22  error  Unexpected use of file extension "js" for "./cypress/plugins/index.js"  import/extensions
Error:   16:25  error  Unexpected trailing comma                                               comma-dangle
Error:   18:56  error  Unexpected trailing comma                                               comma-dangle
Error:   19:4   error  Unexpected trailing comma                                               comma-dangle
Error:   20:3   error  Missing semicolon                                                       semi
```

Can you take care of those so we can confirm tests are passing.

**Comment by radovix** [comment]
@yoshitaka7 feel free to run `yarn lint-fix` as it should fix most of above mentioned errors. If some of them are not fixed automatically, then resolve those manually.

**Review by AleksandarDev — APPROVED** [review]
Everything looks good to me

**Comment by AleksandarDev** [comment]
@yoshitaka7 Thank you for your contribution 👏 🥳

**Pull request merged**
